
# Main configurations
TITLE = "Currency Converter"
VERSION = 0.2
AUTHOR = "Sebastian Wehner"

# Main Window
WIDTH = 600
HEIGHT = 400
TOPOFFSET = 100
LEFTOFFSET = 400

# Top Banner
BANNERWIDTH = WIDTH
BANNERHEIGHT = HEIGHT//6

# Bottom content
CONTENTWIDTH = WIDTH
CONTENTHEIGHT = HEIGHT - BANNERHEIGHT

# Value group configurations
INPUTFIELDHEIGHT = 40

# Conversionbutton configurations
CONVERSIONBUTTONWIDTH = 40
CONVERSIONBUTTONHEIGHT = CONVERSIONBUTTONWIDTH